////
////  ViewController.swift
////  AV Foundation
////
////  Created by Pranjal Satija on 5/22/17.
////  Copyright © 2017 Pranjal Satija. All rights reserved.
////
//
//import UIKit
//import Photos
//
//class TakeAPhotoViewController: UIViewController {
//    
//    @IBOutlet fileprivate var captureButton: UIButton!
//    
//    ///Displays a preview of the video output generated by the device's cameras.
//    @IBOutlet fileprivate var capturePreviewView: UIView!
//    
//    ///Allows the user to put the camera in photo mode.
//    @IBOutlet fileprivate var photoModeButton: UIButton!
//    @IBOutlet fileprivate var toggleCameraButton: UIButton!
//    @IBOutlet fileprivate var toggleFlashButton: UIButton!
//    
//    let cameraController = CameraController()
//    
//    override var prefersStatusBarHidden: Bool { return true }
//    
//    var images: [GoogleOCR] {
//        get {
//            let sort = NSSortDescriptor(key: "date", ascending: false)
//            return DataController.taskLoadData(type: GoogleOCR.self, search: nil, sort: sort)
//        }
//    }
//    
//}
//
////MARK: - App life Cycle
//extension TakeAPhotoViewController {
//    override func viewDidLoad() {
//        
//        func configureCameraController() {
//            cameraController.prepare {(error) in
//                if let error = error {
//                    print(error)
//                }
//                
//                try? self.cameraController.displayPreview(on: self.capturePreviewView)
//            }
//        }
//        
//        func styleCaptureButton() {
//            captureButton.layer.borderColor = UIColor.black.cgColor
//            captureButton.layer.borderWidth = 2
//            
//            captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
//        }
//        
//        styleCaptureButton()
//        configureCameraController()
//    }
//}
//
////MARK: - IBAction
//extension TakeAPhotoViewController {
//    
//    @IBAction func libraryPhotoButtonPressed(_ sender: UIButton) {
//        PresentaionManager.share.show(vc: .MainController)
//    }
//    
//    @IBAction func toggleFlash(_ sender: UIButton) {
//        if cameraController.flashMode == .on {
//            cameraController.flashMode = .off
//            toggleFlashButton.setImage(#imageLiteral(resourceName: "Flash Off Icon"), for: .normal)
//        }
//            
//        else {
//            cameraController.flashMode = .on
//            toggleFlashButton.setImage(#imageLiteral(resourceName: "Flash On Icon"), for: .normal)
//        }
//    }
//    
//    @IBAction func captureImage(_ sender: UIButton) {
//        cameraController.captureImage {(image, error) in
//            guard let image = image else {
//                print(error ?? "Image capture error")
//                return
//            }
//            
//            GoogleAPI.taskDetect(form: image) { (result) in
//                guard let result = result else {
//                    print("Don't have any text in image")
//                    return
//                }
//                DataController.shared.viewContext.delete(self.images[self.images.count-1])
//                DataController.saveContext()
//                
//                let object = GoogleOCR(context: DataController.shared.viewContext)
//                object.image = image.jpegData(compressionQuality: 0.5)
//                object.text = result.fullTextAnnotation.text
//                object.date = Date()
//                DataController.saveContext()
//            }
//            
//            let object = GoogleOCR(context: DataController.shared.viewContext)
//            object.text = K.Text.processing
//            object.image = image.jpegData(compressionQuality: 0.5)
//            object.date = Date()
//            DataController.saveContext()
//            try? PHPhotoLibrary.shared().performChangesAndWait {
//                PHAssetChangeRequest.creationRequestForAsset(from: image)
//            }
//        }
//    }
//}
